[tools]
deno = "2.1.9"
node = "22"

[env]
_.file = '.env.development'

[tasks.install]
run = "pnpm install"

[tasks.backend]
depends = ["install"]
run = "pnpm supabase start"

[tasks.functions]
depends = ["install"]
run = "pnpm supabase functions serve"

[tasks.function-deploy]
depends = ["install"]
run = "pnpm supabase functions deploy"

[tasks.dev]
depends = ["install", "backend"]
run = "pnpm run dev"

[tasks.migrate-up]
depends = ["install"]
run = "pnpm supabase migration up"

[tasks.migrate-down]
depends = ["install"]
run = "pnpm supabase migration down"