[tools]
deno = "2.1.9"
node = "24"

[env]
_.file = '.env.development'

[tasks.install]
description = "Installs dependencies"
run = "pnpm install"

[tasks.backend]
description = "Starts the Supabase backend"
depends = ["install"]
run = "pnpm supabase start"

[tasks.functions]
description = "Starts the Supabase functions"
depends = ["install"]
run = "pnpm supabase functions serve"

[tasks.function-deploy]
description = "Deploys the Supabase functions"
depends = ["install"]
run = "pnpm supabase functions deploy"

[tasks.dev]
description = "Runs the development server"
depends = ["install", "backend"]
run = "pnpm run dev"

[tasks.migrate-up]
description = "Runs the database migration"
depends = ["install"]
run = "pnpm supabase migration up"

[tasks.migrate-down]
description = "Reverts the database migration"
depends = ["install"]
run = "pnpm supabase migration down"

[tasks.pull-production]
description = "Pulls the production database"
depends = ["install"]
run = "pnpm supabase db dump -f supabase/seed.sql --data-only --linked"

[tasks.db-reset]
description = "Resets the database migration"
depends = ["pull-production"]
run = "pnpm supabase db reset --local"

[tasks.backup-db]
description = "Backups the database"
depends = ["install"]
run = "./backup_db.sh"

[tasks.build-android]
description = "Builds the Android app"
depends = ["install"]
run = "pnpm ionic cap build android"
env = { JAVA_HOME="/usr/lib/jvm/java-21-openjdk" }

[tasks.build-android-debug]
description = "Builds the Android app in debug mode"
depends = ["install"]
dir = "{{ config_root }}/android"
run = "fastlane build_debug"
env = { JAVA_HOME="/usr/lib/jvm/java-21-openjdk" }
