[tools]
deno = "2.1.9"
node = "24"

[env]
# _.file = '.env.production'
_.file = '.env.development'

[tasks.install]
description = "Installs dependencies"
run = "pnpm install"

[tasks.backend]
description = "Starts the Supabase backend"
depends = ["install"]
run = "pnpm supabase start"

[tasks.functions]
description = "Starts the Supabase functions"
depends = ["install"]
run = "pnpm supabase functions serve"

[tasks.function-deploy]
description = "Deploys the Supabase functions"
depends = ["install"]
run = "pnpm supabase functions deploy"

[tasks.dev]
description = "Runs the development server"
depends = ["install", "backend"]
run = "pnpm run dev"

[tasks.migrate-up]
description = "Runs the database migration"
depends = ["install"]
run = "pnpm supabase migration up"

[tasks.migrate-down]
description = "Reverts the database migration"
depends = ["install"]
run = "pnpm supabase migration down"

[tasks.pull-production]
description = "Pulls the production database"
depends = ["install"]
run = "pnpm supabase db dump -f supabase/seed.sql --data-only --linked"

[tasks.db-reset]
description = "Resets the database migration"
depends = ["pull-production"]
run = "pnpm supabase db reset --local"

[tasks.backup-db]
description = "Backups the database"
depends = ["install"]
run = "./backup_db.sh"

[tasks.start-emulator]
description = "Starts the Android emulator"
depends = ["install"]
run = "$ANDROID_HOME/emulator/emulator -list-avds"
# run = "$ANDROID_HOME/emulator/emulator -avd Medium_Phone_API_36.0"

[tasks.android-dev]
description = "Builds the Android app"
depends = ["install", "start-emulator"]
run = "pnpm tauri android dev"
env = { "VITE_SUPABASE_URL" = "http://10.0.2.2:55321" }

[tasks.android-build-prod]
description = "Builds the Android app"
depends = ["install"]
run = "pnpm tauri android build"
env = { VITE_SUPABASE_URL = "https://rrjgbneefiwoqvsjwzrz.supabase.co", VITE_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyamdibmVlZml3b3F2c2p3enJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwODUxMDAsImV4cCI6MjA0NzY2MTEwMH0.ywaUYwXnXF555i4dUCCl4gvcTZR1Ct6n0ptheJCdIVw" }

[tasks.android-app-install]
description = "Builds the Android app"
depends = ["android-build-prod"]
run = "adb install -r ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk"
# run = "adb install -r ./src-tauri/gen/android/app/build/outputs/apk/universal/debug/app-universal-debug.apk"
