packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  "core-js": true
  esbuild: true
  sharp: true
  "vue-demi": true
  workerd: true

overrides:
  vue: "3.5.42"
  "@intlify/shared": "11.4.10"
  "@vue/runtime-core": "3.5.42"
  "@vue/runtime-dom": "3.5.42"
  "@vue/reactivity": "3.5.42"
  "@vue/compiler-core": "3.5.42"
  "@vue/compiler-dom": "3.5.42"
  "@vue/compiler-sfc": "3.5.42"
  "@vue/compiler-ssr": "3.5.42"
  "@vue/server-renderer": "3.5.42"
  "@vue/shared": "3.5.42"

packageExtensions:
  vue-sonner:
    peerDependencies:
      nuxt: "-"

patchedDependencies:
  "@onesignal/capacitor-plugin": "patches/@onesignal__capacitor-plugin.patch"
