create table "public"."source" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "user_id" bigint,
    "suggested_at" timestamp without time zone default CURRENT_TIMESTAMP
);


create table "public"."voice_actors" (
    "id" bigint generated by default as identity not null,
    "firstname" text not null,
    "bio" text,
    "nationality" text,
    "date_of_birth" date,
    "awards" text,
    "years_active" text,
    "social_media_links" jsonb,
    "lastname" text not null
);


create table "public"."work" (
    "id" bigint generated by default as identity not null,
    "tmdb_content_id" bigint not null,
    "actor_id" bigint not null,
    "voice_actor_id" bigint,
    "highlight" boolean default false,
    "suggestions" text,
    "status" text default 'suggestion'::text,
    "source_id" bigint
);


CREATE UNIQUE INDEX source_id_key ON public.source USING btree (id);

CREATE UNIQUE INDEX source_pkey ON public.source USING btree (id);

CREATE UNIQUE INDEX unique_firstname_lastname ON public.voice_actors USING btree (firstname, lastname);

CREATE UNIQUE INDEX voice_actors_id_key ON public.voice_actors USING btree (id);

CREATE UNIQUE INDEX voice_actors_pkey ON public.voice_actors USING btree (id);

CREATE UNIQUE INDEX work_id_key ON public.work USING btree (id);

CREATE UNIQUE INDEX work_pkey ON public.work USING btree (id);

alter table "public"."source" add constraint "source_pkey" PRIMARY KEY using index "source_pkey";

alter table "public"."voice_actors" add constraint "voice_actors_pkey" PRIMARY KEY using index "voice_actors_pkey";

alter table "public"."work" add constraint "work_pkey" PRIMARY KEY using index "work_pkey";

alter table "public"."source" add constraint "source_id_key" UNIQUE using index "source_id_key";

alter table "public"."voice_actors" add constraint "unique_firstname_lastname" UNIQUE using index "unique_firstname_lastname";

alter table "public"."voice_actors" add constraint "voice_actors_id_key" UNIQUE using index "voice_actors_id_key";

alter table "public"."work" add constraint "work_id_key" UNIQUE using index "work_id_key";

alter table "public"."work" add constraint "work_source_id_fkey" FOREIGN KEY (source_id) REFERENCES source(id) not valid;

alter table "public"."work" validate constraint "work_source_id_fkey";

alter table "public"."work" add constraint "work_voice_actor_id_fkey" FOREIGN KEY (voice_actor_id) REFERENCES voice_actors(id) not valid;

alter table "public"."work" validate constraint "work_voice_actor_id_fkey";

grant delete on table "public"."source" to "anon";

grant insert on table "public"."source" to "anon";

grant references on table "public"."source" to "anon";

grant select on table "public"."source" to "anon";

grant trigger on table "public"."source" to "anon";

grant truncate on table "public"."source" to "anon";

grant update on table "public"."source" to "anon";

grant delete on table "public"."source" to "authenticated";

grant insert on table "public"."source" to "authenticated";

grant references on table "public"."source" to "authenticated";

grant select on table "public"."source" to "authenticated";

grant trigger on table "public"."source" to "authenticated";

grant truncate on table "public"."source" to "authenticated";

grant update on table "public"."source" to "authenticated";

grant delete on table "public"."source" to "service_role";

grant insert on table "public"."source" to "service_role";

grant references on table "public"."source" to "service_role";

grant select on table "public"."source" to "service_role";

grant trigger on table "public"."source" to "service_role";

grant truncate on table "public"."source" to "service_role";

grant update on table "public"."source" to "service_role";

grant delete on table "public"."voice_actors" to "anon";

grant insert on table "public"."voice_actors" to "anon";

grant references on table "public"."voice_actors" to "anon";

grant select on table "public"."voice_actors" to "anon";

grant trigger on table "public"."voice_actors" to "anon";

grant truncate on table "public"."voice_actors" to "anon";

grant update on table "public"."voice_actors" to "anon";

grant delete on table "public"."voice_actors" to "authenticated";

grant insert on table "public"."voice_actors" to "authenticated";

grant references on table "public"."voice_actors" to "authenticated";

grant select on table "public"."voice_actors" to "authenticated";

grant trigger on table "public"."voice_actors" to "authenticated";

grant truncate on table "public"."voice_actors" to "authenticated";

grant update on table "public"."voice_actors" to "authenticated";

grant delete on table "public"."voice_actors" to "service_role";

grant insert on table "public"."voice_actors" to "service_role";

grant references on table "public"."voice_actors" to "service_role";

grant select on table "public"."voice_actors" to "service_role";

grant trigger on table "public"."voice_actors" to "service_role";

grant truncate on table "public"."voice_actors" to "service_role";

grant update on table "public"."voice_actors" to "service_role";

grant delete on table "public"."work" to "anon";

grant insert on table "public"."work" to "anon";

grant references on table "public"."work" to "anon";

grant select on table "public"."work" to "anon";

grant trigger on table "public"."work" to "anon";

grant truncate on table "public"."work" to "anon";

grant update on table "public"."work" to "anon";

grant delete on table "public"."work" to "authenticated";

grant insert on table "public"."work" to "authenticated";

grant references on table "public"."work" to "authenticated";

grant select on table "public"."work" to "authenticated";

grant trigger on table "public"."work" to "authenticated";

grant truncate on table "public"."work" to "authenticated";

grant update on table "public"."work" to "authenticated";

grant delete on table "public"."work" to "service_role";

grant insert on table "public"."work" to "service_role";

grant references on table "public"."work" to "service_role";

grant select on table "public"."work" to "service_role";

grant trigger on table "public"."work" to "service_role";

grant truncate on table "public"."work" to "service_role";

grant update on table "public"."work" to "service_role";


