

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "unaccent" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."voice_actors" (
    "id" bigint NOT NULL,
    "firstname" "text" NOT NULL,
    "bio" "text",
    "nationality" "text",
    "date_of_birth" "date",
    "awards" "text",
    "years_active" "text",
    "social_media_links" "jsonb",
    "lastname" "text" NOT NULL,
    "profile_picture" "text",
    "tmdb_id" bigint,
    "wikidata_id" "text"
);


ALTER TABLE "public"."voice_actors" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."voice_actor_name"("public"."voice_actors") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE
    AS $_$
  select $1.firstname || ' ' || $1.lastname;
$_$;


ALTER FUNCTION "public"."voice_actor_name"("public"."voice_actors") OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."source" (
    "id" bigint NOT NULL,
    "name" "text",
    "user_id" bigint,
    "suggested_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."source" OWNER TO "postgres";


ALTER TABLE "public"."source" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."source_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."voice_actors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."voice_actors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."work" (
    "id" bigint NOT NULL,
    "content_id" bigint NOT NULL,
    "actor_id" bigint NOT NULL,
    "voice_actor_id" bigint,
    "highlight" boolean DEFAULT false,
    "suggestions" "text",
    "status" "text" DEFAULT 'suggestion'::"text",
    "source_id" bigint,
    "content_type" "text",
    "performance" "text" DEFAULT 'dialogues'::"text"
);


ALTER TABLE "public"."work" OWNER TO "postgres";


ALTER TABLE "public"."work" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."work_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."source"
    ADD CONSTRAINT "source_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."source"
    ADD CONSTRAINT "source_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."voice_actors"
    ADD CONSTRAINT "unique_firstname_lastname" UNIQUE ("firstname", "lastname");



ALTER TABLE ONLY "public"."voice_actors"
    ADD CONSTRAINT "voice_actors_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."voice_actors"
    ADD CONSTRAINT "voice_actors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."work"
    ADD CONSTRAINT "work_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."work"
    ADD CONSTRAINT "work_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."work"
    ADD CONSTRAINT "work_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."source"("id");



ALTER TABLE ONLY "public"."work"
    ADD CONSTRAINT "work_voice_actor_id_fkey" FOREIGN KEY ("voice_actor_id") REFERENCES "public"."voice_actors"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."unaccent"("text") TO "postgres";
GRANT ALL ON FUNCTION "public"."unaccent"("text") TO "anon";
GRANT ALL ON FUNCTION "public"."unaccent"("text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."unaccent"("text") TO "service_role";



GRANT ALL ON FUNCTION "public"."unaccent"("regdictionary", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."unaccent"("regdictionary", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."unaccent"("regdictionary", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."unaccent"("regdictionary", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."unaccent_init"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."unaccent_init"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."unaccent_init"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."unaccent_init"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."unaccent_lexize"("internal", "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."unaccent_lexize"("internal", "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."unaccent_lexize"("internal", "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."unaccent_lexize"("internal", "internal", "internal", "internal") TO "service_role";



GRANT ALL ON TABLE "public"."voice_actors" TO "anon";
GRANT ALL ON TABLE "public"."voice_actors" TO "authenticated";
GRANT ALL ON TABLE "public"."voice_actors" TO "service_role";



GRANT ALL ON FUNCTION "public"."voice_actor_name"("public"."voice_actors") TO "anon";
GRANT ALL ON FUNCTION "public"."voice_actor_name"("public"."voice_actors") TO "authenticated";
GRANT ALL ON FUNCTION "public"."voice_actor_name"("public"."voice_actors") TO "service_role";


















GRANT ALL ON TABLE "public"."source" TO "anon";
GRANT ALL ON TABLE "public"."source" TO "authenticated";
GRANT ALL ON TABLE "public"."source" TO "service_role";



GRANT ALL ON SEQUENCE "public"."source_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."source_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."source_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."voice_actors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."voice_actors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."voice_actors_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."work" TO "anon";
GRANT ALL ON TABLE "public"."work" TO "authenticated";
GRANT ALL ON TABLE "public"."work" TO "service_role";



GRANT ALL ON SEQUENCE "public"."work_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."work_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."work_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
