name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: |
        pnpm install

    - name: Setup Android signing
      run: |
        cd src-tauri/gen/android
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" > keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
        base64 -d <<< "${{ secrets.KEYSTORE_FILE }}" > $RUNNER_TEMP/dubbing-base-keystore.jks
        echo "storeFile=$RUNNER_TEMP/dubbing-base-keystore.jks" >> keystore.properties

    - name: Build Android Release
      if: github.event_name != 'pull_request'
      timeout-minutes: 20
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        pnpm tauri android build

    - name: Upload AAB artifact (Release builds only)
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: android-app-bundle
        path: src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab
        retention-days: 30
      continue-on-error: false

    - name: Upload APK artifact (Release builds)
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-release
        path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
        retention-days: 30
      continue-on-error: false

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download AAB artifact
      uses: actions/download-artifact@v4
      with:
        name: android-app-bundle

    - name: ls
      run: ls -la

    - name: Upload .aab to Production Track
      uses: KevinRohn/github-action-upload-play-store@v1.0.1
      with:
        service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        package_name: "com.dubbingbase.app"
        aab_file_path: "app-universal-release.aab"
        track: "production"
        release_status: "completed"
