name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Fastlane
      run: |
        cd android
        gem install bundler
        bundle install
        bundle exec fastlane validate

    - name: Validate build environment
      run: |
        cd android
        echo "Validating build environment..."
        bundle exec fastlane validate
        echo "Build environment validation completed successfully"

    - name: Build Android Debug (Pull Requests)
      if: github.event_name == 'pull_request'
      timeout-minutes: 15
      env:
        SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      run: |
        cd android
        echo "Starting debug build for pull request..."
        bundle exec fastlane build_debug
        echo "Debug build completed successfully"

    - name: Build Android Release
      if: github.event_name != 'pull_request'
      timeout-minutes: 20
      env:
        SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        cd android
        echo "Starting release build..."
        bundle exec fastlane build_release
        echo "Release build completed successfully"

    - name: Upload AAB artifact (Release builds only)
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: android-app-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 30
      continue-on-error: false

    - name: Upload APK artifact (Release builds)
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-release
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
      continue-on-error: false

    - name: Upload APK artifact (Debug builds)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
      continue-on-error: false
